-- Generated by matugen from the current wallpaper -- edits are overwritten on
-- the next `vela wallpaper`. Source template:
--   ~/.config/vela/templates/hypr-colours.lua
--
-- Required last by hyprland.lua, so these win over the placeholders in
-- general.lua. Hyprland wants rgb()/rgba() with a bare RRGGBB, hence
-- `hex_stripped` throughout.
--
-- hyprlock is a separate hyprlang binary and cannot read Lua, so it gets its
-- own generated file from hypr-colours.conf.

hl.config({
    general = {
        col = {
            -- A gradient is a table with a colors array and an angle; the
            -- hyprlang "colour colour 45deg" string form is not accepted here.
            active_border = {
                colors = {
                    "rgba(9dd49eff)",
                    "rgba(a1ced6ff)"
                },
                angle = 45
            },
            inactive_border = "rgba(42494055)"
        }
    },
    decoration = {
        shadow = {
            color = "rgba(00000055)"
        }
    },
    misc = {
        -- Painted behind everything. The shell draws the wallpaper over it,
        -- so this only shows for the instant before the shell is up.
        background_color = "rgba(101510ff)"
    }
})
