-- Look and feel
--
-- Border and background colours are not here: colours.lua is generated by
-- matugen from the wallpaper and overrides them, and it is required last.

-- How things move, from the shell's own setting (Settings, Appearance,
-- Motion: `animations`, `reduceMotion` and `animationSpeed` in
-- ~/.config/vela/shell.json), so windows move at the pace the shell does.
-- The shell reloads Hyprland when it changes. Read with patterns -- Lua has
-- no JSON parser -- and anything missing or out of range is the default.
local motion = { on = true, reduced = false, speed = 1 }
do
    local dir = os.getenv("XDG_CONFIG_HOME") or ((os.getenv("HOME") or "") .. "/.config")
    local file = io.open(dir .. "/vela/shell.json", "r")
    if file then
        local text = file:read("*a") or ""
        file:close()
        local speed = tonumber(text:match('"animationSpeed"%s*:%s*([%d%.]+)'))
        if speed and speed >= 0.25 and speed <= 4 then
            motion.speed = speed
        end
        motion.on = text:match('"animations"%s*:%s*false') == nil
        motion.reduced = text:match('"reduceMotion"%s*:%s*true') ~= nil
    end
end

-- A duration at that speed: the design's, in tenths of a second, divided.
local function at(ds)
    return ds / motion.speed
end

-- Under reduced motion what slides fades instead, as the shell's own
-- surfaces do.
local function style(moving)
    return motion.reduced and "fade" or moving
end

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 2,
        resize_on_border = true,
        extend_border_grab_area = 12,
        layout = "dwindle",
        allow_tearing = false,
        snap = {
            enabled = true,
            window_gap = 10,
            monitor_gap = 10
        }
    },

    decoration = {
        -- Matches Appearance.rounding in the shell's config.json, so windows
        -- and shell surfaces share one radius.
        rounding = 12,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        blur = {
            enabled = true,
            size = 6,
            passes = 3,
            special = false,
            popups = true,
            noise = 0.015,
            contrast = 1.0,
            brightness = 1.0,
            vibrancy = 0.18
        },
        shadow = {
            enabled = true,
            range = 16,
            render_power = 3
        }
    },

    dwindle = {
        preserve_split = true,
        smart_split = false,
        smart_resizing = true
    },

    master = {
        new_status = "master",
        mfact = 0.55
    },

    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,
        focus_on_activate = false,
        vrr = 0,
        middle_click_paste = false,
        enable_anr_dialog = true
    },

    cursor = {
        inactive_timeout = 5,
        hide_on_key_press = false,
        no_warps = false
    },

    render = {
        direct_scanout = 1
    },

    xwayland = {
        force_zero_scaling = false
    },

    binds = {
        workspace_back_and_forth = false,
        allow_workspace_cycles = true,
        movefocus_cycles_fullscreen = false
    },

    ecosystem = {
        no_update_news = true,
        no_donation_nag = true
    },

    animations = {
        enabled = motion.on
    }
})

-- The shell's motion (docs/motion.md, `Appearance.anim` in the quickshell
-- config), so a window and a panel opening beside it move alike. Speeds are
-- in tenths of a second: 5 is the shell's `morph` and `travel`, 3.5 its
-- `arrive`, 2 its `depart` -- each divided by the speed chosen, like the
-- shell's (`at`, above).
--
--   emphasised  a surface changing size or place -- a window opening, moving,
--               a workspace sliding in -- fast out of the gate, settling late
--   rise        something arriving: fades and layers coming in
--   leave       something going: slow to start, quickest as it disappears
--   standard    small state changes: a border's colour
hl.curve("emphasised", { type = "bezier", points = { { 0.3, 0.9 }, { 0.2, 1 } } })
hl.curve("rise", { type = "bezier", points = { { 0.2, 0.9 }, { 0.2, 1 } } })
hl.curve("leave", { type = "bezier", points = { { 0.3, 0 }, { 0.8, 0.15 } } })
hl.curve("standard", { type = "bezier", points = { { 0.2, 0 }, { 0, 1 } } })

hl.animation({ leaf = "windowsIn", enabled = true, speed = at(5), bezier = "emphasised", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = at(2), bezier = "leave", style = "popin 87%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = at(5), bezier = "emphasised" })
hl.animation({ leaf = "border", enabled = true, speed = at(4), bezier = "standard" })
hl.animation({ leaf = "borderangle", enabled = true, speed = at(20), bezier = "standard" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = at(3.5), bezier = "rise" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = at(2), bezier = "leave" })
hl.animation({ leaf = "fadeSwitch", enabled = true, speed = at(3.5), bezier = "standard" })
hl.animation({ leaf = "fadeShadow", enabled = true, speed = at(3.5), bezier = "standard" })
hl.animation({ leaf = "fadeDim", enabled = true, speed = at(3.5), bezier = "standard" })
-- Other programs' layer surfaces (fuzzel, anything third-party). The shell's
-- own are `no_anim` in rules.lua, because it animates them itself.
hl.animation({ leaf = "layersIn", enabled = true, speed = at(3.5), bezier = "rise", style = style("slide") })
hl.animation({ leaf = "layersOut", enabled = true, speed = at(2), bezier = "leave", style = style("slide") })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = at(3.5), bezier = "rise" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = at(2), bezier = "leave" })
hl.animation({ leaf = "workspaces", enabled = true, speed = at(5), bezier = "emphasised", style = style("slide") })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = at(5), bezier = "emphasised", style = style("slidevert") })

-- Three-finger horizontal swipe changes workspace. Declared here rather than
-- in input.lua because `gesture` is an action, not an input setting.
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
